#!/bin/sh

# The remote branch being pushed to is passed as an argument.
remote_ref="$2"

# Define protected branches
protected_branch_main='refs/heads/main'
protected_branch_master='refs/heads/master'
protected_branch_master='refs/heads/develop'

# Check if the push is targeting a protected branch
if [ "$remote_ref" = "$protected_branch_main" ] || [ "$remote_ref" = "$protected_branch_master" ]; then
  echo "🛑 ERROR: Direct pushes to $remote_ref is forbidden (by hook)."
  exit 1 # Exit with a non-zero status to block the push
fi

exit 0 # Exit with 0 to allow the push
