alias g='git'
alias rebdev='git pull origin develop --rebase=i'
alias rebmas='git pull origin master --rebase=i'
alias rebmai='git pull origin main --rebase=i'
alias rebc='git rebase --continue'
alias rebab='git rebase --abort'
alias pushnew='g push -u origin `git rev-parse --abbrev-ref HEAD`'
alias ck='g checkout'
alias ckb='g checkout -b'
alias pf='g push -f'

alias h='history' 
alias hg='history | grep'

alias v='nvim'
