tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "yqrashawn/goku"

brew "fzf"
brew "hugo"
brew "openjdk"
brew "neovim"
brew "wget"
brew "yqrashawn/goku/goku"

cask "eloston-chromium"
cask "kitty"
cask "notunes"
cask "qmk-toolbox"
cask "raycast"
cask "temurin"
