#!/bin/sh

source "$(dirname "$0")/../scripts/check_protected_branch.sh"

if protected_branch_name=$(is_current_branch_protected); then
    echo "🚫 Committing directly to the protected branch '$protected_branch_name' is not allowed."
    exit 1
fi

exit 0
