vim.cmd('source ~/.vimrc')
require('user.plugins')
require('user.colorscheme')
require('user.cmp')
require('user.lsp')
require('user.treesitter')
require('user.lualine')
require('user.telescope')
require('user.toggleterm')

